<?php

return [
    'programs' => [
        '1' => 'BSIT',
        '2' => 'BSA',
    ],
    'years' => [
        '1' => '1st Year',
        '2' => '2nd Year',
        '3' => '3rd Year',
        '4' => '4th Year',
    ],
    'sections'=> [
        '1',
        '2',
    ],
    'sex' => [
        '1' => 'Male',
        '2' => 'Female',
        '0' => 'Prefer not to say',
    ],
    'gender' => [
        '0' => 'Not Applicable',
    ],
    'civilstatus' => [
        '1' => 'Single',
        '2' => 'Married',
        '3' => 'Widowed',
        '4' => 'Separated',
        '5' => 'Divorced',
    ],
    'roles' => [
        'Developer' => 'Developer',
        'Super Admin' => 'Super Admin',
        'Teacher' => 'Teacher',
    ],
    'educational_attainment' => [
        '1' => 'No schooling completed',
        '2'=> 'Day Care',
        '3'=> 'Kindergarten/Preparatory',
        '4'=> 'Grade 1',
        '5'=> 'Grade 2',
        '6'=> 'Grade 3',
        '7'=> 'Grade 4',
        '8'=> 'Grade 5',
        '9'=> 'Grade 6',
        '10'=> 'Elementary Graduate',
        '11'=> 'Grade 7/Junior High School 1st Year',
        '12'=> 'Grade 8/Junior High School 2nd Year',
        '13'=> 'Grade 9/Junior High School 3rd Year',
        '14'=> 'Grade 10/Junior High School 4th Year',
        '15'=> 'High School Graduate',
        '16'=> 'Grade 11/Senior High School 1st Year',
        '17'=> 'Grade 12/Senior High School 2nd Year',
        '18'=> '1st yr PS(Post Secondary)',
        '19'=> '2nd yr PS(Post Secondary)',
        '20'=> 'Post Secondary/Senior High School Graduate',
        '21'=> '1st yr College',
        '22'=> '2nd yr College',
        '23'=> '3rd yr College',
        '24'=> '4th yr College',
        '25'=> 'College Graduate',
        '26'=> 'Post Graduate with units',
        '27'=> 'Graduate',
    ],
    'occupation' => [
        '1' => 'Officials Of Government And Special Interest Organization, Corporate Executives, Managers, Managing Proprietors, and Supervisor',
        '2' => 'Professionals',
        '3' => 'Technicians and Associate Professionals',
        '4' => 'Clerks',
        '5' => 'Service Workers and Shop and Market Sales Workers',
        '6' => 'Farmers, forestry workers and fisher folk',
        '7' => 'Trades & related workers',
        '8' => 'Plan & machine operators & assemblers',
        '9' => 'Laborers and unskilled workers',
        '10' => 'Special Occupation',
        '11' => 'Housewife',
    ],

];
